name: "Tests Setup"
description: ""
inputs:
  github-token:
    description: ''
    default: ''
    
  steam-appid:
    description: ''
    default: '261550'
  steam-depotid:
    description: ''
    default: '261551'
  steam-login:
    description: ''
    default: ''
  steam-password:
    description: ''
    default: ''
  steam-filefilter:
    description: ''
    default: './.github/resources/FileFilters.regexp'
    
  stable-directory:
    description: ''
    default: 'bannerlord'
  beta-directory:
    description: ''
    default: 'bannerlord-beta'
    
  stable-version:
    description: ''
    default: ''
  beta-version:
    description: ''
    default: ''
    
  depotdownloader-version:
    description: ''
    default: '2.7.1'
  opencover-version:
    description: ''
    default: '4.7.922'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.x.x
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x.x
        
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x
        
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x

    - name: Ensure NuGet Source
      uses: fabriciomurta/ensure-nuget-source@v1
      with:
        name: 'nuget.org'
        url: 'https://api.nuget.org/v3/index.json'

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@v4
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{inputs.github-token}}
        
    - name: Download DepotDownloader_${{inputs.depotdownloader-version}}
      uses: robinraju/release-downloader@v1
      with:
        repository: SteamRE/DepotDownloader
        tag: DepotDownloader_${{inputs.depotdownloader-version}}
        fileName: DepotDownloader-windows-x64.zip

    - name: Extract DepotDownloader_${{inputs.depotdownloader-version}}
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: DepotDownloader-windows-x64.zip
        pathTarget: depotdownloader
        
    - name: Download Game Binaries (Stable)
      run: >-
        if ('${{inputs.stable-version}}' -eq '') { Return };
        depotdownloader/DepotDownloader.exe -app ${{inputs.steam-appid}} -depot ${{inputs.steam-depotid}} -beta ${{inputs.stable-version}} -username ${{inputs.steam-login}}
        -password ${{inputs.steam-password}} -os windows -osarch 64 -filelist ${{inputs.steam-filefilter}} -dir ${{inputs.stable-directory}};
      shell: pwsh
      
    - name: Download Game Binaries (Beta)
      run: >-
        if ('${{inputs.beta-version}}' -eq '') { Return };
        depotdownloader/DepotDownloader.exe -app ${{inputs.steam-appid}} -depot ${{inputs.steam-depotid}} -beta ${{inputs.beta-version}} -username ${{inputs.steam-login}}
        -password ${{inputs.steam-password}} -os windows -osarch 64 -filelist ${{inputs.steam-filefilter}} -dir ${{inputs.beta-directory}};
      shell: pwsh
        
    - name: Download opencover.${{inputs.opencover-version}}
      uses: robinraju/release-downloader@v1
      with:
        repository: OpenCover/opencover
        tag: ${{inputs.opencover-version}}
        file: opencover.${{inputs.opencover-version}}.zip

    - name: Extract opencover.${{inputs.opencover-version}}
      uses: hoatruongdev09/extract-zip@v1.2
      with:
        input-path: opencover.${{inputs.opencover-version}}.zip
        output-path: '${{github.workspace}}/opencover'
